### PR TITLE
[BUGFIX] Resolve rendering warnings

### PR DESCRIPTION
**Pull request by linawolf**
releases: main, 12.4, 11.5

### CODE REVIEW

**Comment by brotkrueml** [comment]
Which warnings?

**Comment by linawolf** [comment]
If you run the tests on the current situation there are two warnings about duplicate confvals

**Comment by brotkrueml** [comment]
So, the other confvals for foreign-table and title should also get a name to be consistent?

**Comment by linawolf** [comment]
This PR is about resolving the warnings, so that the tests are green again. there are many confvals so renaming them all consistently is a task beyond the scope of this PR

**Comment by brotkrueml** [comment]
Personally, I would add all names, which then also removes the warnings (as drive-by). This way now, it is half-baken: you have no warnings anymore, but inconsistent confval configurations - which must be addressed in one or more separate PRs (and not forgotten to do so).

**Review by brotkrueml — APPROVED** [review]
It may be okay for now. But add the other names in near time as separate PRs to be consistent.

**Pull request merged**
