### PR TITLE
Add unique as eval keyword

### PR DESCRIPTION
**Pull request by froemken**
Add a hint to prevent using uniqueInSite within a multi-domain setup.

### CODE REVIEW

**Comment by mbrodala** [comment]
Actually this was already done with #345 but the backport to 10.4 and 9.5 is still missing ...

**Comment by froemken** [comment]
So what should I do? Take the description from master to this patch or remove my updates regarding uniqueInSite but keep new keyword "unique"?

**Comment by mbrodala** [comment]
If you are fine with the master text you can copy it here, then we have at least the 10.4 backport covered already.

Also `unique` is documented properly in `master`, so it would make sense backporting both changes to 10.4.

**Comment by linawolf** [comment]
Backporting between master and 10.4 cannot be done automatically easaly due to the overhaul.

**Comment by linawolf** [comment]
Therefore I manualy inserted the changes from master into this PR. Should we merge it like that, @froemken ?

**Review by mbrodala — APPROVED** [review]

**Comment by froemken** [comment]
@linawolf Perfect. Can be merged. The explanation is much better than my ;-)

**Pull request merged**
