### PR TITLE
Replace dash with underscore

### PR DESCRIPTION
**Pull request by froemken**
Dash does not exists in TCA config properties

### CODE REVIEW

**Comment by mbrodala** [comment]
Would you mind fixing this for [all other `select` types](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/search?q=%22foreign-table%22), too?

**Comment by froemken** [comment]
Yes, I have created 4 further PRs for you

**Comment by mbrodala** [comment]
Thanks. It would be lovely however, if this was a single PR instead since it's about the same topic. Also backports will be easier to keep track of this way. Can you combine all PRs into this one? Cherry-Picking the other commits into the branch of this one should do.

**Comment by froemken** [comment]
Hope this helps. I have closed all other PRs

**Comment by mbrodala** [comment]
Yes, awesome. Thanks a lot!

**Review by mbrodala — APPROVED** [review]

**Comment by susannemoog** [comment]
There is no backport required as the older version was structured differently and already uses underscores.

**Pull request merged**
