### PR TITLE
[TASK] Slightly improve "items" value description

### PR DESCRIPTION
**Pull request by mbrodala**
Ensure values are on 1st level and remarks for these on 2nd level.

### CODE REVIEW

**Comment by marble** [comment]
Hi Mathias, I changed your tabs to three blanks each. And picked a different char to specify the sublist. You can pick any of these characters at any level you want, see [1] "*", "+", "-", "•", "‣", or "⁃", .

Moreover I've indented the whole paragraph "Description" as I would do it: use THREE blanks instead of ONE tab. Do the same for lists, so you can use the tab-key in PhpStorm. Why THREE? Fits best, most beautiful, makes code examples well readable but not tooooo space consuming, and, if that helps, it's in line with the Apple style guide ;-))

[1] http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#bullet-lists

**Comment by mbrodala** [comment]
@marble Thanks for fixing. All I did was pressing `[Tab]` here on Github. ;-)

**Comment by marble** [comment]
Fine! If you wonder about my longy answer: I simply can't help it, I like to let people know :-) And I noticed, you often contribute to documentation. Great!

**Comment by mbrodala** [comment]
I'm always grateful for hints how to improve contributions. :-)

**Pull request closed without merging**
