### PR TITLE
Remove "TCEforms" wrapper in FlexForm definitions

### PR DESCRIPTION
**Pull request by linawolf**
reverences https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/190

### CODE REVIEW

**Comment by linawolf** [comment]
EXT:styleguide was not adjusted yet, it seems. I will regenerate the code snippets in a follow up

**Comment by nhovratov** [comment]
Styleguide is now adjusted. Pushed a commit, which fixes the manual snippets.

**Comment by linawolf** [comment]
Looks good. Can we get this merged or is more work required?

**Review by nhovratov — APPROVED** [review]

**Comment by nhovratov** [comment]
The automatic ones will be merged separately?

**Comment by linawolf** [comment]
yes in a follow up

**Pull request merged**
